- id: redmine-commit-msg
  stages:
    - commit-msg
  name: Redmine Hook for git commits
  description: "Sending info from commits to Redmine"
  entry: redmine_commit_msg
  language: python
  always_run: true
  args: [ ".git/COMMIT_EDITMSG" ]

